name: Daily Reddit Fetcher

on:
  schedule:
    - cron: "30 3 * * *"
  workflow_dispatch:

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create credentials.json
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json

      - name: Run Reddit Fetcher
        run: python reddit_fetcher.py
